name: prestashop_webservice
description: A dart package for reading data from prestashop webservices 
version: 0.3.3
repository: https://github.com/msiviero/prestashop_webservice
topics:
  - api
  - prestashop
  - ecommerce

environment:
  sdk: ^3.0.0

dependencies:
  equatable: ^2.0.5
  http: ^0.13.6
  json_annotation: ^4.8.1
  loggy: ^2.0.3
  quiver: ^3.2.1
  
dev_dependencies:
  build_runner: 
  json_serializable: ^6.7.0
  lints: ^2.0.0
  test: ^1.21.0
